/*
 * *** DO NOT EDIT THIS FILE ***
 *
 * This file contains external declarations for UIParameter objects
 * generated by the "mobu" utility.  If you need to add a parameter,
 * you should go to mobu and add it to the parameters.xml file and
 * regenerate the Classes files.  Failure to do so will result in
 * changes being lost the next time mobu generated files are exported.
 *
 */

#pragma once

/*** GENERATED ***/

extern UIParameter* UIParameterLogStatus;
extern UIParameter* UIParameterActiveSetup;
extern UIParameter* UIParameterActiveOverlay;
extern UIParameter* UIParameterFadeFrames;
extern UIParameter* UIParameterMaxSyncDrift;
extern UIParameter* UIParameterDriftCheckPoint;
extern UIParameter* UIParameterPluginPorts;
extern UIParameter* UIParameterLongPress;
extern UIParameter* UIParameterSpreadRange;
extern UIParameter* UIParameterTraceLevel;
extern UIParameter* UIParameterAutoFeedbackReduction;
extern UIParameter* UIParameterIsolateOverdubs;
extern UIParameter* UIParameterMonitorAudio;
extern UIParameter* UIParameterSaveLayers;
extern UIParameter* UIParameterQuickSave;
extern UIParameter* UIParameterIntegerWaveFile;
extern UIParameter* UIParameterGroupFocusLock;
extern UIParameter* UIParameterTrackCount;
extern UIParameter* UIParameterGroupCount;
extern UIParameter* UIParameterMaxLoops;
extern UIParameter* UIParameterInputLatency;
extern UIParameter* UIParameterOutputLatency;
extern UIParameter* UIParameterMidiInput;
extern UIParameter* UIParameterMidiOutput;
extern UIParameter* UIParameterMidiThrough;
extern UIParameter* UIParameterPluginMidiInput;
extern UIParameter* UIParameterPluginMidiOutput;
extern UIParameter* UIParameterPluginMidiThrough;
extern UIParameter* UIParameterAudioInput;
extern UIParameter* UIParameterAudioOutput;
extern UIParameter* UIParameterNoiseFloor;
extern UIParameter* UIParameterMidiRecordMode;
extern UIParameter* UIParameterSubcycles;
extern UIParameter* UIParameterMultiplyMode;
extern UIParameter* UIParameterShuffleMode;
extern UIParameter* UIParameterAltFeedbackEnable;
extern UIParameter* UIParameterEmptyLoopAction;
extern UIParameter* UIParameterEmptyTrackAction;
extern UIParameter* UIParameterTrackLeaveAction;
extern UIParameter* UIParameterLoopCount;
extern UIParameter* UIParameterMuteMode;
extern UIParameter* UIParameterMuteCancel;
extern UIParameter* UIParameterOverdubQuantized;
extern UIParameter* UIParameterQuantize;
extern UIParameter* UIParameterBounceQuantize;
extern UIParameter* UIParameterRecordResetsFeedback;
extern UIParameter* UIParameterSpeedRecord;
extern UIParameter* UIParameterRoundingOverdub;
extern UIParameter* UIParameterSwitchLocation;
extern UIParameter* UIParameterReturnLocation;
extern UIParameter* UIParameterSwitchDuration;
extern UIParameter* UIParameterSwitchQuantize;
extern UIParameter* UIParameterTimeCopyMode;
extern UIParameter* UIParameterSoundCopyMode;
extern UIParameter* UIParameterRecordThreshold;
extern UIParameter* UIParameterSwitchVelocity;
extern UIParameter* UIParameterMaxUndo;
extern UIParameter* UIParameterMaxRedo;
extern UIParameter* UIParameterNoFeedbackUndo;
extern UIParameter* UIParameterNoLayerFlattening;
extern UIParameter* UIParameterSpeedShiftRestart;
extern UIParameter* UIParameterPitchShiftRestart;
extern UIParameter* UIParameterSpeedStepRange;
extern UIParameter* UIParameterSpeedBendRange;
extern UIParameter* UIParameterPitchStepRange;
extern UIParameter* UIParameterPitchBendRange;
extern UIParameter* UIParameterTimeStretchRange;
extern UIParameter* UIParameterSlipMode;
extern UIParameter* UIParameterSlipTime;
extern UIParameter* UIParameterAutoRecordTempo;
extern UIParameter* UIParameterAutoRecordBars;
extern UIParameter* UIParameterRecordTransfer;
extern UIParameter* UIParameterOverdubTransfer;
extern UIParameter* UIParameterReverseTransfer;
extern UIParameter* UIParameterSpeedTransfer;
extern UIParameter* UIParameterPitchTransfer;
extern UIParameter* UIParameterWindowSlideUnit;
extern UIParameter* UIParameterWindowEdgeUnit;
extern UIParameter* UIParameterWindowSlideAmount;
extern UIParameter* UIParameterWindowEdgeAmount;
extern UIParameter* UIParameterDefaultSyncSource;
extern UIParameter* UIParameterDefaultTrackSyncUnit;
extern UIParameter* UIParameterSlaveSyncUnit;
extern UIParameter* UIParameterManualStart;
extern UIParameter* UIParameterMinTempo;
extern UIParameter* UIParameterMaxTempo;
extern UIParameter* UIParameterBeatsPerBar;
extern UIParameter* UIParameterMuteSyncMode;
extern UIParameter* UIParameterResizeSyncAdjust;
extern UIParameter* UIParameterSpeedSyncAdjust;
extern UIParameter* UIParameterRealignTime;
extern UIParameter* UIParameterOutRealign;
extern UIParameter* UIParameterActiveTrack;
extern UIParameter* UIParameterTrackName;
extern UIParameter* UIParameterPreset;
extern UIParameter* UIParameterFocus;
extern UIParameter* UIParameterGroup;
extern UIParameter* UIParameterMono;
extern UIParameter* UIParameterFeedback;
extern UIParameter* UIParameterAltFeedback;
extern UIParameter* UIParameterInput;
extern UIParameter* UIParameterOutput;
extern UIParameter* UIParameterPan;
extern UIParameter* UIParameterSyncSource;
extern UIParameter* UIParameterTrackSyncUnit;
extern UIParameter* UIParameterAudioInputPort;
extern UIParameter* UIParameterAudioOutputPort;
extern UIParameter* UIParameterPluginInputPort;
extern UIParameter* UIParameterPluginOutputPort;
extern UIParameter* UIParameterSpeedOctave;
extern UIParameter* UIParameterSpeedStep;
extern UIParameter* UIParameterSpeedBend;
extern UIParameter* UIParameterPitchOctave;
extern UIParameter* UIParameterPitchStep;
extern UIParameter* UIParameterPitchBend;
extern UIParameter* UIParameterTimeStretch;
