/**
 * *** DO NOT EDIT THIS FILE ***
 *
 * This file contains UIParameter subclasses and static object definitions
 * generated by the "mobu" utility.  If you need to add a parameter,
 * you should go to mobu and add it to the parameters.xml file and
 * regenerate the Classes files.  Failure to do so will result in
 * changes being lost the next time mobu generated files are exported.
 *
 * The brief section above the GENERATED token is static and will not
 * be replaced during generation.   It should only contain the includes
 * necessary to compile the file in the mobu environment.
 * Projucer must be configured to find those files in the main Mobius source tree.
 *
 */

#include <JuceHeader.h>

#include "../util/Util.h"
#include "../model/ExValue.h"
#include "../model/MobiusConfig.h"
#include "../model/Preset.h"
#include "../model/Setup.h"

#include "UIParameter.h"

