/*
 * *** DO NOT EDIT THIS FILE ***
 *
 * This file contains external declarations for UIParameter objects
 * generated by the "mobu" utility.  If you need to add a parameter,
 * you should go to mobu and add it to the parameters.xml file and
 * regenerate the Classes files.  Failure to do so will result in
 * changes being lost the next time mobu generated files are exported.
 *
 */

#pragma once

