/**
 * Auto generated by Projucer
 * Not sure how much we can do with this without Projucer overwriting
 * it if the configuration changes.
 */
#pragma once

#include <JuceHeader.h>

#include "ui/MainMenu.h"
#include "ui/ConfigEditor.h"
#include "ui/TestPanel.h"
#include "ui/TableTest.h"
#include "ui/TabTest.h"

//==============================================================================
/*
    This component lives inside our window, and this is where you should put all
    your controls and content.
*/
class MainComponent  : public juce::AudioAppComponent, public MainMenu::Listener
{
  public:
    //==============================================================================
    MainComponent();
    ~MainComponent() override;

    //==============================================================================
    void prepareToPlay (int samplesPerBlockExpected, double sampleRate) override;
    void getNextAudioBlock (const juce::AudioSourceChannelInfo& bufferToFill) override;
    void releaseResources() override;

    //==============================================================================
    void paint (juce::Graphics& g) override;
    void resized() override;

    //
    // Start Mobius additions
    //

    // MainMenu listener
    void mainMenuSelection(int id);
    
  private:

    class MobiusInterface* mobius;

    class MainMenu mainMenu;

    ConfigEditor configEditor {this};
    TestPanel test;
    TableTest table;
    TabTest tabs;
    
    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (MainComponent)
};
